### ISSUE TITLE
Check box and select all not working in admin

### ISSUE THREAD

**Issue by scrimpys** [app-generator/django-admin-black#13]
I am not able to see a check box above the list of items in my admin panel.  For example I have a model called People.  When using the default Django install I am able to see a check box that allows me to select all items on that page. With the Django admin black enabled I can see that check box.  See images below.

Django Black Admin 
![image](https://github.com/app-generator/django-admin-black/assets/25236569/c04225a0-4e91-4adc-8c0a-fce6aa263117)

Default Django 
![image](https://github.com/app-generator/django-admin-black/assets/25236569/da57e06d-9a63-41ef-9fe6-01a43f4ff51b)

Note the little check box next to the ID in the second image.

**Comment by app-generator** [comment]
Hello @scrimpys 
The problem is fixed in version `v1.0.8`
Please check.

**Comment by scrimpys** [comment]
ok - thanks but it doesn't select all the boxes when checked.  That's what the box is for.  I noticed another issue just opened about fixing select all which I think will fix this... hope it does.

**Comment by app-generator** [comment]
@mominur-helios please check the point raised by @scrimpys 
Ty both!

**Comment by mominur-helios** [comment]
Hello @scrimpys , 
It should work. Did you pull the latest version?


https://github.com/app-generator/django-admin-black/assets/101915710/fc2f0110-4720-4f9a-9e36-1c2ecd094a9a

**Comment by scrimpys** [comment]
Tested it again.... not working.  I cleared my cache and tried that as well.  I am seeing this in the browser console - perhaps this can help although I suspect its just something to do with the demo charts.

jQuery.Deferred exception: null is not an object (evaluating 'document.getElementById("chartLinePurple").getContext') 
"initDashboardPageCharts@http://192.168.1.220:8000/static/assets/demo/demo.js:352:57
@http://192.168.1.220:8000/admin/precision/person/:905:37
j@http://192.168.1.220:8000/static/assets/js/core/jquery.min.js:2:30004
@http://192.168.1.220:8000/static/assets/js/core/jquery.min.js:2:30314"
undefined

**Comment by app-generator** [comment]
Hello @scrimpys 

The patch shipped by @mominur-helios works. 
The problem is the local assets & templates that need also updated because Django uses the local filesystem with PRIO over the VENV.

Please test using the latest version of Django Black Dashboard:

https://github.com/app-generator/django-black-dashboard

The patch is visible on this commit: 

https://github.com/app-generator/django-black-dashboard/commit/34e5a2defff8f70f7b70e5a88a7986a98b31bc58

**Comment by scrimpys** [comment]
OK awesome support guys ... will test.  Need to do this carefully though so will take some time.

**Comment by app-generator** [comment]
🚀🚀

**Comment by scrimpys** [comment]
thanks guys, tested and working.
