### ISSUE TITLE
The model User is not registered

### ISSUE THREAD

**Issue by salahuddinshaikh** [app-generator/django-admin-black#6]
Hi, I am using custom user model, when I am trying to setup admin-black it throws exception NotRegistered('The model %s is not registered' % model.__name__), django.contrib.admin.sites.NotRegistered: The model User is not registered.

**Comment by app-generator** [comment]
Hello @salahuddinshaikh

@imankarimi can you assist?

**Comment by imankarimi** [comment]
Hello @salahuddinshaikh 
Yeah, I can see this. it's because we are customizing the user model too. in the next version, we will fix this bug.
