### ISSUE TITLE
[Django 4.0.1] cannot import name 'smart_text' from 'django.utils.encoding' 

### ISSUE THREAD

**Issue by KenzoKai** [app-generator/django-admin-black#7]
This happens when installing in existing project.

Django 4.0.1

`django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'admin_black.templatetags.admin_black': cannot import name 'smart_text' from 'django.utils.encoding' (/usr/local/lib/python3.9/site-packages/django/utils/encoding.py)`

**Comment by app-generator** [comment]
Hello @KenzoKai, 

The issue has been patched. The new package will be released soon on PyPi.

Until then, you can install the latest version via `PIP`:

```bash
$ pip uninstall django-admin-black
$ pip install git+https://github.com/app-generator/django-admin-black.git
```

Let us know your progress.

**Comment by app-generator** [comment]
Ty @imankarimi :)
